name: GitHub Pages
on: 
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    container: node:16.17
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependences
        uses: actions/setup-node@v3
        with:
          node-version: 16.17
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: cp ./dist/index.html ./dist/404.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist'
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v1
